### ISSUE TITLE
Class not found error

### ISSUE THREAD

**Issue by MsFakhra** [apanimesh061/VaderSentimentJava#7]
Hi,

I am trying to use the jar file. I just copied your code and it is not working giving me following error

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at com.vader.sentiment.analyzer.SentimentAnalyzer.<clinit>(SentimentAnalyzer.java:59)
	at GenerateSentiment.main(GenerateSentiment.java:31)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

PS: I have downloaded and added jar file and imported the class like
import com.vader.sentiment.analyzer.SentimentAnalyzer;

Any idea what i am doing wrong?

**Comment by papadako** [comment]
Hi, you need the following dependencies

`    <dependencies>
        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-analyzers-common</artifactId>
            <version>${lucene.analyzers.common.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>21.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.6</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.6.4</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.github.apanimesh061</groupId>
            <artifactId>vader-sentiment-analyzer</artifactId>
            <version>1.0</version>
        </dependency>
    </dependencies>`

**Comment by AbsolomKahara** [comment]
@MsFakhra Did it work after providing the dependency. Am having the same problem while working on my project and I dont know how to go about it.

**Comment by apanimesh061** [comment]
Hi all,
I know this a very late response and apologies for the delay.
I have updated the package and its README so that it becomes easy for any user to use the new versions as a maven dependency.

Please let me know if it still somehow does not work.

Thanks.
